# 𝓒𝓸𝓭𝓮𝓭 𝓫𝔂 𝓔𝔁𝓸𝓼𝓶𝓲𝓾𝓶 (vk.com/prodbyhakin)
# Спасибо, что используете мой плагин!

# Параметры сообщений плагина
[messages]
    cooldown = "&4&lНагр&c&lады &8&l» &f Поиграйте еще, чтобы получить данную награду!"
    exist = "&4&lНагр&c&lады &8&l» &f Вы уже получили &6данную награду."
    given = "&4&lНагр&c&lады &8&l» &f Награда была успешно выдана!"
    does-not-exist = "&4&lНагр&c&lады &8&l» &f Данной награды &cне существует!"
    cooldown-title = ["&4&lОй...", "Поиграйте еще, чтобы получить &cэту награду."]
    exist-title = ["&6&lХе-хе!", "Вы уже получили &eданную награду."]


# Параметры настроек плагина
[settings]
    # Количество наград
    reward-count = 2

# Награды
[1]
    actions = [
        "[survival] crazycrates give v free 1 {player}",
    ]
    title = ["&6&lБуууум!", "Вы получили &eбесплатный кейс!"]
    required-time = { survival = 5 }

[2]
    actions = [
        "[survival] crazycrates give v free 1 {player}",
    ]
    title = ["&6&lПоздравляем!", "Вы получили &cбесплатный кейс!"]
    required-time = { survival = 999999 }